### ISSUE TITLE
ArithmeticException

### ISSUE THREAD

**Issue by rflpazini** [karamsa/android-radar#3]
Hello man, I'm try to using this repo. But when I call the method refresh(), this returns the exception: 

12-07 14:02:21.514 4098-4098/com.lospernas.snc E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.lospernas.snc, PID: 4098
                                                                 java.lang.ArithmeticException: divide by zero
                                                                     at com.rflpazini.radar.Radar.drawPins(Radar.java:182)
                                                                     at com.rflpazini.radar.Radar.makeRadar(Radar.java:146)
                                                                     at com.rflpazini.radar.Radar.onDraw(Radar.java:106)
                                                                     at android.view.View.draw(View.java:17185)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3711)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3691)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16130)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1379)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16162)
                                                                     at android.view.View.draw(View.java:16951)
                                                                     at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
                                                                     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
                                                                     at android.view.View.draw(View.java:17188)
                                                                     at com.android.internal.policy.DecorView.draw(DecorView.java:753)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:16167)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:648)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:654)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:762)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2800)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2608)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2215)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

If you can help me, I will be great full

**Comment by karamsa** [comment]
Hello, 
Tank you for using this module.
Tell me about your android version. and how you pass the points?
Thanks

**Comment by rflpazini** [comment]
I'm using android 7.1.1 Nougat on my Nexus 5x.
On my app I used play services location to get long and lat of the device. How it is double I converted it to float and pass to the radar using the class RadarPoint.

**Comment by karamsa** [comment]
Hello, 
It's resolved. https://github.com/karamsa/android-radar/commit/9a1f831782dce27ca0b18e0bd7bdfee8a11ce9dd
Clone the module and test.
Thanks
